### ISSUE TITLE
Add Native 1.2 Support

### ISSUE THREAD

**Issue by dbemiller** [mxmCherry/openrtb#20]
It looks like the latest version of OpenRTB Native 1.2 has been released: https://iabtechlab.com/wp-content/uploads/2016/07/OpenRTB-Native-Ads-Specification-Final-1.2.pdf

There are a few more fields in this version which could be added to the project.

**Comment by mxmCherry** [comment]
I'll definitely take a look into this over next weekend (Feb 24-25). But PRs are welcome at any time :)

**Comment by dbemiller** [comment]
sure thing! I'll start some of it this week if I have time, but... can't promise anything.

**Comment by mxmCherry** [comment]
Started https://github.com/mxmCherry/openrtb/pull/21

**Comment by mxmCherry** [comment]
I was really surprised by how shitty that 1.2 spec is done.

First - no (working) links in PDF.

Then some inconsistencies for new type(s):
- starting with really minor "type: text" instead of usual "type: string" in 5.8 Event Tracker Response Object - "url" field description
- proceeding (ending?) with really frustrating 5.8 Event Tracker Response Object - "customdata" field: "type: object	 containing key:value pairs" and "description: ... an array of 
key:value objects ..." (luckily, that doesn't matter for implementation, as it's better done as RawJSON)

I didn't expect good quality from these docs, but it outperformed my expectations.

Then I decided to check https://www.iab.com/guidelines/real-time-bidding-rtb-project/

(drumroll...)

Native 1.2 is still Draft for Public Review (just with review period ended on May 17, 2017), it's not released yet :smile: 

And it looks like ad-tech world (including it's authors) ignored it (I have no other explanation for poor document's state since May 2017).

Anyway, I've almost done it https://github.com/mxmCherry/openrtb/pull/21 , I'll, probably, finish it till next Monday (Mar 6).

But I'm not sure I would like to merge deadborn Native 1.2 into master until it's officially released (if it'll ever be). Probably, I'll merge, but I don't promise anything. Probably, if prebid-server really needs it (I doubt it), we could make/keep dedicated `native-1.2-dev` branch.

Does any exchange support it already? (I'd expect none yet, but haven't followed Native news for quite a while)

**Comment by mxmCherry** [comment]
Though document name has Final in it :thinking: But I'd defo better wait till it's linked from some "official" page.

**Comment by dbemiller** [comment]
yeesh.... you're right.

As far as official pages go, it is linked from [here](https://iabtechlab.com/blog/openrtb-native-version-1-2-finalized/). ...but I notice that there's no "Release date" on it, the way there is for the other versions.

[This blog post](https://iabtechlab.com/blog/openrtb-native-version-1-2-finalized/) also looks official, and mentions that the Native group went on hiatus right afterwards. Maybe the "core" IAB group didn't like it either?

I'll poke around some slack channels and get back to you. There's got to be someone connected to the IAB who can give us the story.

Def don't feel obligated to merge it or keep a dedicated branch for it just for us... we've got the same goal here. If it's not yet official, it shouldn't be in prebid-server either.

**Comment by dbemiller** [comment]
I asked in the reddit adops slack channel. Jennifer Derke confirmed that Native 1.2 is official and finalized, and the `iab.com` link needs to be updated. She also said that a few companies have started implementing it.

She's the [product director](https://iabtechlab.com/about-the-iab-tech-lab/tech-lab-team/) of the IAB Tech Lab, so... should be a fair authority ^^.

**Comment by mxmCherry** [comment]
Pubished on https://www.iab.com/guidelines/real-time-bidding-rtb-project/ page:

https://www.iab.com/wp-content/uploads/2018/03/OpenRTB-Native-Ads-Specification-Final-1.2.pdf

For now - will add this link to repo docs.

Though https://iabtechlab.com/ looks to be more suitable resource to reference OpenRTB specs ¯\_(ツ)_/¯

**Comment by mxmCherry** [comment]
https://github.com/mxmCherry/openrtb/pull/21 merged

**Comment by mxmCherry** [comment]
Released as [v10.0.0](https://github.com/mxmCherry/openrtb/releases/tag/v10.0.0)
