### ISSUE TITLE
Field "Value" in metric.go

### ISSUE THREAD

**Issue by dianhua1560** [mxmCherry/openrtb#26]
Reference: https://github.com/mxmCherry/openrtb/blob/fd8bfbb100a0523846df3fb83875fd2e5f3cd8c2/metric.go#L28 

Since the "Value" field is a float between [0.0, 1.0] and and GO defaults float to 0.0, this field can not be validated if it is provided and auto-set by default.

Proposing: pointer for this field?

Any other thoughts?

**Comment by mxmCherry** [comment]
Sounds sensible.

But I still feel a bit uneasy about this, because, IMO, this lib is not very suitable for validation, tbh (not only this case can be a bit problematic to validate, I think)

I'd leave this as is, and allow it to default to 0 if omitted - I think, strict validations for this exact field could be traded for simplicity (avoid pointers).

Though, if you really need this, I will accept PR, as it makes sense and follows OpenRTB specs:
- [ ] change this field to `*float64`
- [ ] add `Float64Ptr(n float64) *float64` helper here: https://github.com/mxmCherry/openrtb/blob/master/ptr.go

**Comment by mxmCherry** [comment]
Closing this for now. Still open for PR, if really needed.
